language: android
android:
  components:
    #- platform-tools
    #- tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script:
   - ./gradlew build connectedCheck
   
before_install:
   - chmod +x gradlew
   
notifications:
  slack: epic-productions:6xnziz4cgS04gmXSnvUMYeHO